### ISSUE TITLE
SimpleFlowTest.testFlowWithGlobalSession unstable

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/cloud-slang#241]
2015-04-12 19:15:12 ERROR SlangImpl:60 - Failed compilation for source : flow_with_missing_navigation_from_op_result.sl ,Exception is : Cannot compile flow: 'basic_flow' since for task: 'Task1', the result 'CUSTOM' of its dependency: 'user.ops.print_custom_result_op' has no matching navigation
Tests run: 7, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.219 sec <<< FAILURE! - in io.cloudslang.lang.systemtests.SimpleFlowTest
testFlowWithGlobalSession(io.cloudslang.lang.systemtests.SimpleFlowTest)  Time elapsed: 0.037 sec  <<< ERROR!
java.lang.RuntimeException: Error running: Task1.
	Input with name: 'port' is Required, but value is empty
	at io.cloudslang.lang.systemtests.TriggerFlows.runSync(TriggerFlows.java:56)
	at io.cloudslang.lang.systemtests.SystemsTestsParent.trigger(SystemsTestsParent.java:43)
	at io.cloudslang.lang.systemtests.SimpleFlowTest.testFlowWithGlobalSession(SimpleFlowTest.java:111)

https://travis-ci.org/CloudSlang/cloud-slang/jobs/58185357

**Comment by oritstone** [comment]
Not reproducable
