### ISSUE TITLE
when "bash cslang run" (cslang from bash cmd) cslang not closing properlly 

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/cloud-slang#299]
Of course an error should be printed for the missing "--f" arg (that is printed) but why JPA error is printed?? should close nicely:

May 13, 2015 4:37:29 AM org.springframework.shell.core.SimpleParser parse
WARNING: You should specify a default option (otherwise known as option 'f') for this command
Exception in thread "Thread-3" org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.service.UnknownServiceException: Unknown service requested [org.hibernate.service.jdbc.connections.spi.ConnectionProvider]
        at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:430)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:457)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:276)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
        at com.sun.proxy.$Proxy80.updateEnvironmentParams(Unknown Source)
        at io.cloudslang.worker.management.services.WorkerManager$1.run(WorkerManager.java:191)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.hibernate.service.UnknownServiceException: Unknown service requested [org.hibernate.service.jdbc.connections.spi.ConnectionProvider]
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:151)
        at org.hibernate.internal.AbstractSessionImpl.getJdbcConnectionAccess(AbstractSessionImpl.java:262)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.<init>(JdbcCoordinatorImpl.java:106)
        at org.hibernate.engine.transaction.internal.TransactionCoordinatorImpl.<init>(TransactionCoordinatorImpl.java:90)
        at org.hibernate.internal.SessionImpl.<init>(SessionImpl.java:254)
        at org.hibernate.internal.SessionFactoryImpl$SessionBuilderImpl.openSession(SessionFactoryImpl.java:1618)
        at org.hibernate.ejb.EntityManagerImpl.getRawSession(EntityManagerImpl.java:121)
        at org.hibernate.ejb.EntityManagerImpl.getSession(EntityManagerImpl.java:97)
        at org.hibernate.ejb.AbstractEntityManagerImpl.setDefaultProperties(AbstractEntityManagerImpl.java:273)
        at org.hibernate.ejb.AbstractEntityManagerImpl.postInit(AbstractEntityManagerImpl.java:181)
        at org.hibernate.ejb.EntityManagerImpl.<init>(EntityManagerImpl.java:89)
        at org.hibernate.ejb.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:193)
        at org.hibernate.ejb.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:188)
        at org.springframework.orm.jpa.JpaTransactionManager.createEntityManagerForTransaction(JpaTransactionManager.java:448)
        at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:369)

**Comment by meirwah** [comment]
on ubuntu 14.04, cslang version 7.29

**Comment by meirwah** [comment]
does not reproduce with 0.8 version...
