### ISSUE TITLE
Python action - Cannot import svn.local

### ISSUE THREAD

**Issue by oritstone** [CloudSlang/cloud-slang#406]
When trying to import in an action python script, we get:
 
```
Command failed java.lang.RuntimeException: Slang Error : Error executing python script: Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "C:\Users\stoneo\Desktop\Cslang-0.8-rc-1\cslang\python-lib\svn\local.py", line 4, in <module>
    import svn.common
  File "C:\Users\stoneo\Desktop\Cslang-0.8-rc-1\cslang\python-lib\svn\common.py", line 4, in <module>
    import dateutil.parser
  File "C:\Users\stoneo\Desktop\Cslang-0.8-rc-1\cslang\python-lib\dateutil\parser.py", line 22, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
```

If we first import in our script StringIO from io nmaually, it works:
```python
      from io import StringIO
      import svn.local
```

**Comment by orius123** [comment]
So, 
The workaround I'm going to implement now is importing io when loading jython.
will open issue to jython.

**Comment by oritstone** [comment]
:+1:
