### ISSUE TITLE
loop for range(1,0) error during navigation

### ISSUE THREAD

**Issue by varelasavela** [CloudSlang/cloud-slang#412]
If you try to do loop for `range(1,0)` , you get exception :
```bash
 Caused by: java.lang.RuntimeException: Error evaluating for loop expression in task 'UpdateFile',
	Error is: expression is empty
	at io.cloudslang.lang.runtime.bindings.LoopsBinding.createForLoopCondition(LoopsBinding.java:114)
	at io.cloudslang.lang.runtime.bindings.LoopsBinding.getOrCreateLoopCondition(LoopsBinding.java:52)
	at io.cloudslang.lang.runtime.steps.TaskSteps.beginTask(TaskSteps.java:75)
	... 14 more
2015-08-11 14:45:17,288 [1_WorkerExecutionThread-11_124100057] (ReflectionAdapterImpl.java:72) ERROR - Failed to run the action! Class: io.cloudslang.lang.runtime.navigations.Navigations, method: navigate, reason: Error running: UpdateFile: Error evaluating for loop expression in task 'UpdateFile',
	Error is: expression is empty
```

**Comment by orius123** [comment]
After evaluating the loop expression we don't check if it's empty. 
Since it's iterable by definition we can check `hasNext()`

**Comment by orius123** [comment]
Actually I see that the exception states exactly the problem. (we have the hasMore() check). 
Don't think we can do anymore here.

**Comment by orius123** [comment]
@varelasavela anything I'm missing or can I close this one?

**Comment by meirwah** [comment]
@varelasavela ??
