### ISSUE TITLE
read_from_file operation context serialization error

### ISSUE THREAD

**Issue by varelasavela** [CloudSlang/cloud-slang#413]
If score tries to create execution message during this operation execution (for example if isRunningTooLong), it fails because  PyFile object, which is serializable  itself ,has field file:TextIOWrapper which is not serializable.

```bash
(SimpleExecutionRunnable.java:126) ERROR - Error during execution!!!
java.lang.RuntimeException: Failed to serialize execution plan. Error: 
	at io.cloudslang.engine.queue.entities.ExecutionMessageConverter.objToBytes(ExecutionMessageConverter.java:100)
	at io.cloudslang.engine.queue.entities.ExecutionMessageConverter.createPayload(ExecutionMessageConverter.java:45)
	at io.cloudslang.engine.queue.entities.ExecutionMessageConverter.createPayload(ExecutionMessageConverter.java:41)
	at io.cloudslang.worker.management.services.SimpleExecutionRunnable.createInProgressExecutionMessage(SimpleExecutionRunnable.java:387)
	at io.cloudslang.worker.management.services.SimpleExecutionRunnable.isRunningTooLong(SimpleExecutionRunnable.java:330)
	at io.cloudslang.worker.management.services.SimpleExecutionRunnable.shouldStop(SimpleExecutionRunnable.java:175)
	at io.cloudslang.worker.management.services.SimpleExecutionRunnable.executeRegularStep(SimpleExecutionRunnable.java:161)
	at io.cloudslang.worker.management.services.SimpleExecutionRunnable.run(SimpleExecutionRunnable.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at io.cloudslang.worker.management.services.WorkerThreadFactory$1.run(WorkerThreadFactory.java:33)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.NotSerializableException: org.python.core.io.TextIOWrapper
```

**Comment by orius123** [comment]
It happens because we store all variables in the action context for the output bindings.
IMHO we need to pass only certain types i.e (strings,sets,lists,maps..)

**Comment by meirwah** [comment]
can we fix this to this version @orius123 ?
or can we leave it as limitation?

**Comment by orius123** [comment]
we can do both :smile:

**Comment by meirwah** [comment]
What you think is the right path for this version?

**Comment by orius123** [comment]
It's our content so we need to fix it

**Comment by meirwah** [comment]
Which flow? I do not see any flow mentioned in this bug?

**Comment by orius123** [comment]
files content.
read from file for example

**Comment by orius123** [comment]
I'ts actually the name of the issue..

**Comment by orius123** [comment]
@meirwah do you agree in the solution?

**Comment by meirwah** [comment]
sorry missed this..

**Comment by meirwah** [comment]
yes.. let's fix this operation
question is... does this happen in other content we have?

**Comment by oritstone** [comment]
I don't think we need to fix our content, we need to fix the behavior - support only Serializable types

**Comment by meirwah** [comment]
this is a change you want to do now??? for this version?

**Comment by orius123** [comment]
we cant fix the operation. only the code.
