### ISSUE TITLE
message is not cleared which thrown when precompile failed

### ISSUE THREAD

**Issue by hajyhia** [CloudSlang/cloud-slang#752]
how to reproduce:

create .sl file with only namesapce line

2016-06-26 11:29:56,960 [taskExecutor-1] (ImportProjectServiceImpl.java:135) INFO  - CloudSlang failed to compile source file notvalid
2016-06-26 11:29:56,968 [taskExecutor-1] (SlangLanguagePlugin.java:313) ERROR - Failed to load slang file: "notvalid.sl", Error transforming source: notvalid to a Slang model. Source notvalid has no content associated with flow/operation/properties property.
java.lang.RuntimeException: Error transforming source: notvalid to a Slang model. Source notvalid has no content associated with flow/operation/properties property.
               at io.cloudslang.lang.compiler.modeller.SlangModellerImpl.createModel(SlangModellerImpl.java:43)
               at io.cloudslang.lang.compiler.SlangCompilerImpl.preCompileSource(SlangCompilerImpl.java:90)
               at com.hpe.webstudio.languageplugin.slang.SlangLanguagePlugin.getExecutable(SlangLanguagePlugin.java:303)
               at com.hpe.webstudio.languageplugin.slang.SlangLanguagePlugin.convertToOOSTDataObject(SlangLanguagePlugin.java:91)
               at com.hpe.webstudio.elements.services.ContentElementsServiceImpl.getOOSTDataObject(ContentElementsServiceImpl.java:851)
               at com.hpe.webstudio.elements.services.ContentElementsServiceImpl.createFlow(ContentElementsServiceImpl.java:443)
               at com.hpe.webstudio.elements.services.ContentElementsServiceImpl.createElement(ContentElementsServiceImpl.java:275)
               at com.hpe.webstudio.elements.services.ContentElementsServiceImpl.createElement(ContentElementsServiceImpl.java:250)
               at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
               at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
               at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
               at java.lang.reflect.Method.invoke(Method.java:497)
               at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
               at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
               at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
               at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
               at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
               at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
               at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
               at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
               at com.sun.proxy.$Proxy145.createElement(Unknown Source)
               at com.hpe.webstudio.project.services.ImportProjectServiceImpl.extractFiles(ImportProjectServiceImpl.java:138)
               at com.hpe.webstudio.project.services.ImportProjectServiceImpl.lambda$importProjectContent$7(ImportProjectServiceImpl.java:83)
               at com.hpe.webstudio.project.services.ImportProjectServiceImpl$$Lambda$34/283720518.accept(Unknown Source)
               at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
               at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
               at java.util.Iterator.forEachRemaining(Iterator.java:116)
               at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
               at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)

**Comment by Bonczidai** [comment]
@hajyhia can you please provide more details here? what would be the expected behavior?

**Comment by Bonczidai** [comment]
closing for now
