### ISSUE TITLE
Validate step declares exact dependency results in navigation section

### ISSUE THREAD

**Issue by maayannoy** [CloudSlang/cloud-slang#808]
missing navigation in step means that it has default behavior.
in case the original step results does not contain failure and success (only the two of them) we want the compilation to fail.

**Comment by maayannoy** [comment]
example for this:
op1: contains result custom
flow1 contain step:
   step1:
     do:
       op1:
without navigation section.
by default it means that on success it will go to next step, and failure to on-failure.
but, op1 contains only custom result.
need to show compilation error.

**Comment by Bonczidai** [comment]
if you have op

```yaml
operation:
  ...
  results:
    - EVEN: ${ isEven and not tooBig }
    - ODD: ${ not(isEven or tooBig) }
    - CUSTOM
```

and flow

```yaml
flow:
  workflow:
    - check_number:
        do: ...
        publish:
          - new_number: ${ preprocessed_number }
```

it throws:
```console
Caused by: java.lang.IllegalArgumentException: Cannot compile flow: 'flow_complex_navigation' since for step: 'check_number', the result 'EVEN' of its dependency: 'user.ops.check_number' has no matching navigation
	at io.cloudslang.lang.compiler.validator.CompileValidatorImpl.validateDependenciesResultsHaveMatchingNavigations(CompileValidatorImpl.java:125)
	at io.cloudslang.lang.compiler.validator.CompileValidatorImpl.validateStepAgainstItsDependency(CompileValidatorImpl.java:109)
	at io.cloudslang.lang.compiler.validator.CompileValidatorImpl.validateModelWithDependencies(CompileValidatorImpl.java:90)
	at io.cloudslang.lang.compiler.validator.CompileValidatorImpl.validateModelWithDependencies(CompileValidatorImpl.java:38)
	at io.cloudslang.lang.compiler.scorecompiler.ScoreCompilerImpl.compile(ScoreCompilerImpl.java:75)
	at io.cloudslang.lang.compiler.SlangCompilerImpl.compile(SlangCompilerImpl.java:88)
	at io.cloudslang.lang.api.SlangImpl.compile(SlangImpl.java:64)
	... 37 more
```

this is from score-compile phase (after pre-compile) since you need the flow dependencies.

- can you use the `io.cloudslang.lang.compiler.SlangCompiler#validateSlangModelWithDirectDependencies` method?
- other possiblity maybe to extend the score-compile phase to accumulate the errors like pre-compile (in that case your p[re-compile(flow) calls should be replaced with compile(flow, dependencies))

So we need to understand what you really need.. WDYT?

**Comment by Bonczidai** [comment]
```
operation:
  name: check_number
  python_action:
    script: pass
  # no results declared -> SUCCESS
----------------------------------
workflow:
    - check_number:
        do:
          ops.check_number: ..
        # no navigate section
```

Step with default navigation (SUCCESS->SUCCESS, FAILURE->handle FAILURE), but the underlying dependency may have only SUCCESS or FAILURE.

`check that all subflow results are wired` should also check that we don’t have unreachable navigation keys on the step (step declares the exact results - not more, not less)

**Comment by dumagalex** [comment]
Please verify navigate section of Parallel Loop  does not require users to define navigation for inner step results different from SUCCESS & FAILURE (the other ones are evaluated to SUCCESS)

**Comment by Bonczidai** [comment]
@dumagalex checked it, no problem - thanks for pointing out this case
